export const scaleFactor = 4;

export const dialogData = {
    pc: `On the monitor of the PC, there are several windows open. One is a code editor with an in-progress JavaScript project open; the cursor blinks at the end of line 176. Another is a browser showing the <a href="https://github.com/megleedev" target="_blank">Github</a> account of megleedev; a brunette developer smiles back at you. Repositories of projects written in C++, C#, Go, JavaScript, and Python peek from the bottom of the screen.`,
    degree: `A few degrees and certificates decorate the wall. One is a Bachelor's degree in English Literature from Mississippi State University, another is a Master's in Game Design from Full Sail University, and the last is a certificate from The Tech Academy's Game Developer Bootcamp program. The frames are all black and the glass has been cleaned recently.`,
    "sofa-table": `Across the back of the sofa there is a a blue blanket embroidered with the word "Psyonix" draped. In the empty seats, there are a few miscellaneous items scattered around. A pair of headphones, a half-empty water bottle, and a closed laptop. The laptop has a sticker on the back that reads "I'd rather be coding."`,
    "game-console": 'A fifth generation game console sits beside the television. Several game cases are stacked on top of it. Although the selection of games appears to be diverse, the game on top of the pile is an RPG. The controller is plugged in but it rests across the floor towards the sofa.',
    tv: `A video titled "lofi hip hop radio" plays on mute. The recently watched videos listed in the sidebar cover subjects on game design analysis, ideas for programming projects, and tutorials on aspects of the Unreal Engine.`,
    bed: `The bed is made with a white comforter and a few pillows. The comforter is slightly rumpled, as if someone had been sitting on it recently. A few books, loose pages, and a blue Western Governers University pen are resting in a circle around the bed; a half-completed study session.`,
    resume: `On the desk, there is an iPad with a resume displayed on screen. <a href="https://github.com/megleedev/megleedev/blob/main/Meghan_Lee_Resume_GH.pdf" target="_blank">Scroll through it?</a>`,
    projects: `Written documentation about this portfolio is scribbled on the pages of a red college-ruled notebook. It reads: Made with the Kaboom.js library which is a library for making games in JavaScript.
    Text is rendered with HTML/CSS so the textbox you're currently reading is not rendered within canvas.`,
    "book-case": `On the tiered bookcase there are rows and rows of books. On the top few shelves there are written works of fiction in the sci-fi, fantasy, and historical fiction genres. On the bottom shelves there are heavier textbooks on everything from game engine architecture, animation, drawing, programming languages, and programming theory.`,
    exit: `If you want to exit Meg's portfolio, just close the tab. If you'd like to send me a message, please click the "Contact me!" button at the top right of the screen. Thank you for playing!`,
};